name = "modern-react-app"
main = "worker.js"
compatibility_date = "2024-09-18"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "modern-react-app-prod"

# AI Model bindings for Cloudflare Workers AI
[ai]
binding = "AI"

# Environment variables
[vars]
ENVIRONMENT = "production"