name = "chittytrace"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-18"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "chittytrace-prod"

# Environment variables
[vars]
ENVIRONMENT = "production"
VITE_REGISTRY_URL = "https://registry.chitty.cc"