# ChittyConnect Configuration for ChittyTrace-CC
service:
  name: ChittyTrace-CC
  display_name: ChittyTrace CC
  type: service
  tier: 4
  organization: CHITTYAPPS
  chitty_id: ${CHITTYTRACE_CC_SERVICE_ID}
  domains:
    production: trace-cc.chitty.cc

onboarding:
  endpoint: https://get.chitty.cc/api/onboard
  provisions: [chitty_id, service_token, certificate, trust_chain]

auth:
  provider: chittyauth
  endpoint: https://auth.chitty.cc
  service_token:
    source: chittyconnect
    key: CHITTYTRACE_CC_SERVICE_TOKEN

secrets:
  provider: chittyconnect
  vault: 1password
  paths:
    production: op://ChittyOS/ChittyTrace-CC-prod

github:
  repository: CHITTYAPPS/ChittyTrace-CC

monitoring:
  health:
    endpoint: /health
    interval: 60s
