name = "flow-analyzer"
main = "src/index.js"
compatibility_date = "2024-01-15"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "DOCUMENTS_KV"
id = "your_kv_namespace_id"

[durable_objects]
bindings = [
  { name = "ANALYSIS_SESSION", class_name = "AnalysisSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["AnalysisSession"]

[build]
command = "npm run build"
cwd = "./"
watch_dir = "src"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[placement]
mode = "smart"